apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: example-http-binding
spec:
  type: bindings.http
  metadata:
  - name: url
    value: http://localhost:8080/bind
  - name: method
    value: POST