apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: receive
spec:
  type: bindings.http
  metadata:
  - name: url
    value: http://localhost:8081/receive
  - name: method
    value: POST
scopes:
  - producer