apiVersion: apps/v1
kind: Deployment
metadata:
  name: formatter
  namespace: trace
  labels:
    app: formatter
    env: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: formatter
  template:
    metadata:
      labels:
        app: formatter
        env: demo
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "formatter"
        dapr.io/port: "8082"
        dapr.io/log-as-json: "true"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: service
        image: mchmarny/dapr-formatter-demo:v0.1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: PORT
          value: "8082"
        - name: DAPR_HTTP_PORT
          value: "3500"