apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: trace
  labels:
    app: producer
    env: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
        env: demo
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "producer"
        dapr.io/port: "8081"
        dapr.io/log-as-json: "true"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: service
        image: mchmarny/dapr-producer-demo:v0.1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8082"
        - name: DAPR_HTTP_PORT
          value: "3500"