apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
  namespace: trace
  labels:
    app: subscriber
    env: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
        env: demo
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "subscriber"
        dapr.io/port: "8083"
        dapr.io/log-as-json: "true"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: user-container
        image: mchmarny/dapr-subscriber-demo:v0.1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        env:
        - name: PORT
          value: "8082"
        - name: DAPR_HTTP_PORT
          value: "3500"
